const Constants = {
    CLOUDINARY_PRESET: 'r62k0ahs',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dsdrqyeh1/image/upload',
    SIGN_UP_API: 'http://190.98.210.42/sos_click_api/public/api/auth/signup',
    SIGN_IN_API: 'http://190.98.210.42/sos_click_api/public/api/auth/login',
    USER_INFO_API: 'http://190.98.210.42/sos_click_api/public/api/auth/user',
    LOG_OUT_API: 'http://190.98.210.42/sos_click_api/public/api/auth/logout',
    EDIT_USER_API: 'http://190.98.210.42/sos_click_api/public/api/auth/user/editar',
    UPDATE_PHOTO_API: 'http://190.98.210.42/sos_click_api/public/api/auth/user/editarFotoPerfil',
    SIGN_UP: 'SIGN_UP',
    SHOW_SPINNER: 'SHOW_SPINNER',
    HIDE_SPINNER: 'HIDE_SPINNER',
    SIGN_IN: 'SIGN_IN',
    AUTHENTICATED_TRUE: 'AUTHENTICATED_TRUE',
    AUTHENTICATED_FALSE: 'AUTHENTICATED_FALSE',
    USER_INFO_LOAD: 'USER_INFO_LOAD',
    SAVE_USER_INFO: 'SAVE_USER_INFO',
    LOG_OUT: 'LOG_OUT',
    SAVE_CONTACTS: 'SAVE_CONTACTS',
    CLEAN_CONTACTS: 'CLEAN_CONTACTS',
    EDIT_USER: 'EDIT_USER',
    GO_BACK_TRUE: 'GO_BACK_TRUE',
    GO_BACK_FALSE: 'GO_BACK_FALSE',
    OPEN_GALLERY: 'OPEN_GALLERY',
    SAVE_PHOTO: 'SAVE_PHOTO',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL'
};

export default Constants;